### ISSUE TITLE
Ошибка парсинга профиля. Скорее всего, когда до битвы несколько секунд

### ISSUE THREAD

**Issue by kruglikoff** [Iriskin0/Chat-Wars-Bot#108]
> Exception during chatwars automation process:  int() argument must be a string, a bytes-like object or a number, not 'NoneType'
> Traceback (most recent call last):
>   File "./main.py", line 1468, in main
>     a.loop()
>   File "./main.py", line 550, in loop
>     self.hero_parser(m)
>   File "./main.py", line 952, in hero_parser
>     self.time_to_war = int(m.group(1)) * 60 + int(m.group(2))
> TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by Loskir** [comment]
вроде должно быть пофикшено

**Comment by blazeis** [comment]
в телетоновской версии точно не пофикшено
